### ISSUE TITLE
undefined method `represented'

### ISSUE THREAD

**Issue by Tab10id** [apotonick/reform#248]
Hi.
I'm try to use 2.0.1 with nested form:

``` Ruby
class PostCommitActionForm < Reform::Form
  include Reform::Form::ModelReflections

  property :action_type, virtual: true
  property :description
  property :url
  property :condition_group,
           prepopulator: :prepopulate_condition_group!,
           populate_if_empty: PostCommitAction::ConditionGroup,
           form: PostCommitAction::ConditionGroupForm

  private

  def prepopulate_condition_group!(options)
    self.condition_group = PostCommitAction::ConditionGroup.new(cond_type: 'and'))
  end
end

class PostCommitAction::ConditionGroupForm < Reform::Form
  include Reform::Form::ModelReflections

  model 'post_commit_action/condition_group'
  property :cond_type
end
````

In controller:
``` Ruby
PostCommitActionForm.new(PostCommitAction.new).validate(params[:post_commit_action])
```
Got error:
```
undefined method `represented' for #<PostCommitAction::ConditionGroupForm:0xbad5b3fc>

/home/tab10id/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/reform-ca8ca05e2a80/lib/reform/form/validate.rb:73:in `block (2 levels) in deserializer'
uber (0.0.13) lib/uber/options.rb:80:in `instance_exec'
uber (0.0.13) lib/uber/options.rb:80:in `proc!'
uber (0.0.13) lib/uber/options.rb:69:in `evaluate_for'
uber (0.0.13) lib/uber/options.rb:60:in `evaluate'
representable (2.2.3) lib/representable/binding.rb:127:in `evaluate_option'
representable (2.2.3) lib/representable/deserializer.rb:30:in `deserialize'
representable (2.2.3) lib/representable/deserializer.rb:23:in `call'
representable (2.2.3) lib/representable/populator.rb:35:in `deserialize'
representable (2.2.3) lib/representable/populator.rb:21:in `call'
representable (2.2.3) lib/representable/binding.rb:85:in `read_fragment'
representable (2.2.3) lib/representable/binding.rb:64:in `block in uncompile_fragment'
representable (2.2.3) lib/representable/binding.rb:120:in `evaluate_option'
representable (2.2.3) lib/representable/binding.rb:63:in `uncompile_fragment'
representable (2.2.3) lib/representable/mapper.rb:77:in `uncompile_fragment'
representable (2.2.3) lib/representable/mapper.rb:38:in `deserialize_property'
representable (2.2.3) lib/representable/mapper.rb:18:in `block in deserialize'
representable (2.2.3) lib/representable/mapper.rb:17:in `each'
representable (2.2.3) lib/representable/mapper.rb:17:in `deserialize'
representable (2.2.3) lib/representable.rb:41:in `update_properties_from'
representable (2.2.3) lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
representable (2.2.3) lib/representable/hash.rb:31:in `from_hash'
/home/tab10id/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/reform-ca8ca05e2a80/lib/reform/form/validate.rb:55:in `deserialize'
/home/tab10id/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/reform-ca8ca05e2a80/lib/reform/form/validate.rb:25:in `validate'
```

Am I doing something wrong or it is a bug? Comment '# FIXME: we could also get a new deserializer here.' looks scary=)

**Comment by Tab10id** [comment]
Update:
Works fine if I define nested form in PostCommitActionForm

But in real project in ConditionGroupForm I have
``` Ruby
collection :condition_groups, form: PostCommitAction::ConditionGroupForm
collection :conditions, form: PostCommitAction::ConditionForm
```

So... I can't define it in PostCommitActionForm

**Comment by apotonick** [comment]
This is fixed in Disposable 0.1.8.

**Comment by achernik** [comment]
Hi Nick! Should updating Disposable gem be enough? I've done that, but still get the same error

**Comment by apotonick** [comment]
Please also pull reform/master. I forgot to push yesterday! :grin:
